import puppeteer from 'puppeteer-core'
import path from 'node:path'

const browser = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const page = await browser.newPage()
await page.setViewport({ width: 440, height: 956, deviceScaleFactor: 1 })
await page.goto('http://127.0.0.1:4174', { waitUntil: 'networkidle0' })

const shot = async (name, fullPage = false) => page.screenshot({ path: path.resolve('tmp', `${name}.png`), fullPage })
const settle = async () => {
  await page.waitForNetworkIdle({ idleTime: 250 })
  await page.evaluate(() => Promise.all(Array.from(document.images, (image) => image.complete ? image.decode().catch(() => undefined) : new Promise((resolve) => image.addEventListener('load', resolve, { once: true })))))
}
await shot('flow-01-home')
await page.click('.ref-home-start')
await settle()
await shot('flow-02-verify')
await page.type('#student-id', 's4123456')
await page.click('.verify-next')
await settle()
await shot('flow-03-avatar', true)
await page.click('.avatar-choice-grid button:nth-child(4)')
await page.click('.avatar-next')
await settle()
await shot('flow-04-profile', true)
await page.type('.ref-field:nth-child(1) input', 'Year 3')
await page.type('.ref-field:nth-child(2) input', 'Digital Marketing')
await page.click('.info-next')
await settle()
await shot('flow-05-setup', true)
await page.click('.document-options .setup-card:nth-child(3)')
await page.click('.setup-next')
await settle()
await shot('flow-06-intro', true)
await page.click('.intro-help')
await page.waitForSelector('.intro-rule-modal')
await page.mouse.click(10, 900)
await page.waitForSelector('.intro-rule-modal', { hidden: true })
await page.$eval('.intro-review', (button) => button.click())
await settle()
await shot('flow-07-overview', true)
await page.click('.interview-section-list button:nth-child(1)')
await settle()
await shot('flow-08-gameplay', true)
  await page.click('.game-help')
  await page.click('.hint-dismiss')
await page.click('.answer-line:nth-child(2)')
await page.click('.section-submit')
await page.waitForSelector('.done-button')
await page.$eval('.done-button', (button) => button.click())
await page.waitForSelector('.overview-screen')

await browser.close()
